import type { Metadata } from 'next';
import './globals.css';
import NavBar from '@/app/components/NavBar';

import { Just_Another_Hand } from 'next/font/google';
import { NextFont } from 'next/dist/compiled/@next/font';
import Providers from '@/app/Providers';

export const metadata: Metadata = {
  title: "Meg's Comfort Creations",
  description: 'Generated by create next app',
};

const JAH: NextFont = Just_Another_Hand({ weight: '400', subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={JAH.className}>
        <Providers>
          <NavBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
