import type { Metadata } from 'next';
import './globals.css';
import NavBar from '@/components/shared/NavBar';

import { Just_Another_Hand } from 'next/font/google';
import { NextFont } from 'next/dist/compiled/@next/font';
import Providers from '@/Providers';
import { TRPCProvider } from 'lib/trpc/provider';

export const metadata: Metadata = {
  title: "Meg's Comfort Creations",
  description: 'Generated by create next app',
  icons: {
    icon: '/Comfort.png',
  },
};

const JAH: NextFont = Just_Another_Hand({ weight: '400', subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={JAH.className}>
        <TRPCProvider>
          <Providers>
            <NavBar />
            {children}
          </Providers>
        </TRPCProvider>
      </body>
    </html>
  );
}
